"""Make manager_dn nullable in DepartmentManager for outside managers

Revision ID: 7878593d8b5a
Revises: b224a2065ce2
Create Date: 2025-12-05 19:21:13.818407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7878593d8b5a'
down_revision = 'b224a2065ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_manager', schema=None) as batch_op:
        batch_op.alter_column('manager_dn',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_manager', schema=None) as batch_op:
        batch_op.alter_column('manager_dn',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)

    # ### end Alembic commands ###
