"""Add is_outside_manager and manager_display_name for external managers

Revision ID: b224a2065ce2
Revises: babae4da5083
Create Date: 2025-12-05 18:27:15.103785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b224a2065ce2'
down_revision = 'babae4da5083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop temp table if it exists from failed migration
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_user_direct_report")
    
    # Add columns directly
    op.add_column('user_direct_report', sa.Column('manager_display_name', sa.String(length=256), nullable=True))
    op.add_column('user_direct_report', sa.Column('is_outside_manager', sa.Boolean(), nullable=False, server_default=sa.text("'0'")))
    
    # Make manager_dn nullable
    with op.batch_alter_table('user_direct_report', schema=None) as batch_op:
        batch_op.alter_column('manager_dn',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_direct_report', schema=None) as batch_op:
        batch_op.alter_column('manager_dn',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.drop_column('is_outside_manager')
        batch_op.drop_column('manager_display_name')

    # ### end Alembic commands ###
