"""Add is_outside_supervisor field for external supervisors

Revision ID: babae4da5083
Revises: 29d4432ec92b
Create Date: 2025-12-05 18:20:45.245150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babae4da5083'
down_revision = '29d4432ec92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_direct_report', schema=None) as batch_op:
        # Add new columns for outside supervisors
        batch_op.add_column(sa.Column('supervisor_display_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('is_outside_supervisor', sa.Boolean(), nullable=False, server_default=sa.text("'0'")))
        
        batch_op.alter_column('is_indirect_report',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_dotted_line',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.create_index('idx_employee_primary', ['employee_username'], unique=True, postgresql_where=sa.text('is_dotted_line = false'))
        batch_op.create_index(batch_op.f('ix_user_direct_report_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_direct_report_employee_username'), ['employee_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_direct_report_manager_username'), ['manager_username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_direct_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_direct_report_manager_username'))
        batch_op.drop_index(batch_op.f('ix_user_direct_report_employee_username'))
        batch_op.drop_index(batch_op.f('ix_user_direct_report_department'))
        batch_op.drop_index('idx_employee_primary', postgresql_where=sa.text('is_dotted_line = false'))
        batch_op.alter_column('is_dotted_line',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_indirect_report',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        
        # Remove new columns
        batch_op.drop_column('is_outside_supervisor')
        batch_op.drop_column('supervisor_display_name')

    # ### end Alembic commands ###
